import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execute } from "../runtime.mjs";

const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "shipping-mode-"));
assert.equal(execute("init", [], cwd).status, "APPLIED");
execute("config", ["--name", "Demo"], cwd);
const release = execute("release", ["--name", "Release 1"], cwd);
const item = execute("item", ["--name", "Item 1", "--release", release.operations[0].parent_id || "release"], cwd);
execute("work-package", ["--name", "WP 1", "--item", item.operations[0].parent_id || "item"], cwd);
execute("task", ["--name", "Task 1", "--work-package", "wp-1"], cwd);
const proposed = execute("propose", ["--kind", "task", "--name", "Proposed task"], cwd);
assert.equal(execute("apply", ["--changeset", proposed.id], cwd).status, "APPLIED");
assert.equal(execute("check", [], cwd).status, "PASS");
assert.equal(execute("report", [], cwd).status, "READY");
assert.equal(fs.existsSync(path.join(cwd, ".planning", "events", "journal.jsonl")), true);
assert.equal(fs.existsSync(path.join(cwd, ".planning", "operations")), true);
console.log("vertical slice tests: init, config, release, item, work-package, task, propose, apply, check and report passed");
