import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { runConfiguredGuideGenerator } from "../customGuideGenerator.mjs";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "guide-generator-"));
const writeExecutable = (name, source) => { const file = path.join(root, name); fs.writeFileSync(file, `#!/usr/bin/env node\n${source}`); fs.chmodSync(file, 0o755); return file; };
writeExecutable("generator.mjs", "let data=''; process.stdin.on('data', c => data += c).on('end', () => process.stdout.write(JSON.stringify({openGaps: [], sourceRefs: JSON.parse(data).sourceRefs, inheritedSecret: process.env.SHIPPING_MODE_TEST_SECRET || null})));\n");
const input = { sourceRefs: ["018f0000-0000-7000-8000-000000000011"] };
process.env.SHIPPING_MODE_TEST_SECRET = "must-not-leak";
const result = runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "generator.mjs", args: [] }, input });
assert.deepEqual(result.output.sourceRefs, input.sourceRefs);
assert.equal(result.output.inheritedSecret, null);
assert.equal(result.inputHash.length, 64);
assert.equal(result.outputHash.length, 64);
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "../outside.mjs", args: [] }, input }), /relative workspace path|escapes root/);
const outside = fs.mkdtempSync(path.join(os.tmpdir(), "outside-generator-"));
const outsideFile = path.join(outside, "outside.mjs");
fs.writeFileSync(outsideFile, "#!/usr/bin/env node\nprocess.stdout.write('{}');"); fs.chmodSync(outsideFile, 0o755);
fs.symlinkSync(outsideFile, path.join(root, "escape.mjs"));
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "escape.mjs", args: [] }, input }), /symlink escapes root/);
writeExecutable("bad.mjs", "process.stdout.write(JSON.stringify({status:'approved'}));");
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "bad.mjs", args: [] }, input }), /server-owned field/);
writeExecutable("slow.mjs", "setTimeout(() => {}, 1000);");
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "slow.mjs", args: [] }, input, timeoutMs: 20 }), /timeout/);
writeExecutable("huge.mjs", "process.stdout.write('x'.repeat(20000));");
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "huge.mjs", args: [] }, input, maxOutputBytes: 1024 }), /output exceeds limit/);
writeExecutable("malformed.mjs", "process.stdout.write('not-json');");
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "malformed.mjs", args: [] }, input }), /not valid JSON/);
writeExecutable("nonzero.mjs", "process.stderr.write('sensitive-output'); process.exit(7);");
assert.throws(() => runConfiguredGuideGenerator({ workspaceRoot: root, generator: { version: "1", executable: "nonzero.mjs", args: [] }, input }), (error) => /exited with code 7/.test(error.message) && !error.message.includes("sensitive-output"));
console.log("custom-guide-generator: confinement, symlink escape, minimal env, bounded output, redacted failures, structured I/O, hashes, and timeout pass");
